### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by gleporeNARA** [datacoon/metawarc#3]
I like both of the analyze and metadata commands, however in my agency we need a detailed file listing that includes things like file name, byte size, file extension, preferably in CSV output. I understand the need for JSON output for the detailed metadata, but is there a chance for a new switch that outputs detailed information as above in CSV format? Not including the repeating fields with extracted data for the specific file types.

Thanks!

**Comment by gleporeNARA** [comment]
Ivan - I hear you. We're just in the process of identifying tools to deal with WARC files. I wasn't able to get webarchive-discovery working (due to the reliance on an old version of Java.) And Replay-web is a brute to work with and didn't load all of our test files. I will test out warcio and other tools, but we also need something that works in a Windows environment. It's surprising after 15 years of WARC being a standard, there still aren't the necessary tools to view and authenticate the data.

**Comment by ivbeg** [comment]
@ivbeg sure! If warcio wouldn't work great I will add this command.
